# Aldaron's Device Interface - Storage - Demo                                  #
# Copyright (c) 2017 Plop Grizzly, Jeron Lau <jeron.lau@plopgrizzly.com>       #
# Licensed under the MIT LICENSE                                               #
#                                                                              #
# examples/storage/details.toml                                                #

name = "%storage"
comment = "%comment"
description = "%read the root directory and user's username"
